# Generated by Django 3.2 on 2021-06-12 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2021, 6, 12, 9, 38, 49, 242050))),
                ('token_name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(default=datetime.datetime(2021, 6, 12, 9, 38, 49, 242050))),
                ('unassigned_at', models.DateTimeField(default=datetime.datetime(2021, 6, 12, 9, 38, 49, 242050))),
                ('is_assigned_alive', models.BooleanField(default=False)),
                ('alive_alive_at', models.DateTimeField(default=datetime.datetime(2021, 6, 12, 9, 38, 49, 242050))),
                ('is_alive', models.BooleanField(default=False)),
                ('alive_at', models.DateTimeField(default=datetime.datetime(2021, 6, 12, 9, 38, 49, 242050))),
            ],
            options={
                'db_table': 'Token',
            },
        ),
    ]
