# Generated by Django 3.2 on 2021-06-12 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0006_auto_20210612_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='alive_alive_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 11, 25, 58, 69754)),
        ),
        migrations.AlterField(
            model_name='token',
            name='alive_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 11, 25, 58, 69754)),
        ),
        migrations.AlterField(
            model_name='token',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 11, 25, 58, 69754)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 11, 25, 58, 69754)),
        ),
        migrations.AlterField(
            model_name='token',
            name='unassigned_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 11, 25, 58, 69754)),
        ),
    ]
