# Generated by Django 3.2 on 2021-06-15 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0015_auto_20210615_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='alive_at',
        ),
        migrations.RemoveField(
            model_name='token',
            name='unassigned_at',
        ),
        migrations.AlterField(
            model_name='token',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 16, 31, 35, 272480)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 16, 31, 35, 272480)),
        ),
    ]
